### ISSUE TITLE
Migration fails on fresh install

### ISSUE THREAD

**Issue by samfrjn11** [JustinByrne/Mealing#9]
I'm getting following error while running a fresh migration:

` SQLSTATE[HY000]: General error: 1553 Cannot drop index 'meal_menu_meal_id_foreign': needed in a foreign key constraint (SQL: ALTER TABLE menu_recipe CHANGE meal_id recipe_id BIGINT UNSIGNED NOT NULL)`

While `Migrating: 2021_06_28_181444_rename_meals_table_to_recipe_table` 

Not sure how to fix

**Comment by JustinByrne** [comment]
Thanks, I'll have a look at this and get this sorted soon

**Comment by JustinByrne** [comment]
I am having issues trying to replicate this issue. Could you provide some more information about your system?

**Comment by samfrjn11** [comment]
@JustinByrne You have fixed it already in d0605600512ad2c585076b0055d9831f9170f4a8 but it seems like you didn't reference it back then. At that point I also wasn't 100% sure that this commit was the actual fix for this issue and later on I forgot about it. Apologies for that!

**Comment by JustinByrne** [comment]
Thank you for letting me know, I hadn't realised to be honest.

**Comment by wahyusaragih** [comment]
I still have this problem while migrating on a fresh installation

   Illuminate\Database\QueryException

  SQLSTATE[HY000]: General error: 1553 Cannot drop index 'meal_menu_meal_id_foreign': needed in a foreign key constraint (SQL: ALTER TABLE menu_recipe CHANGE meal_id recipe_id BIGINT UNSIGNED NOT NULL)

  at F:\Laravel\Mealing\vendor\laravel\framework\src\Illuminate\Database\Connection.php:692
    688▕         // If an exception occurs when attempting to run a query, we'll format the error
    689▕         // message to include the bindings with SQL, which will make this exception a
    690▕         // lot more helpful to the developer instead of just the database's errors.
    691▕         catch (Exception $e) {
  ➜ 692▕             throw new QueryException(
    693▕                 $query, $this->prepareBindings($bindings), $e
    694▕             );
    695▕         }
    696▕

  1   F:\Laravel\Mealing\vendor\laravel\framework\src\Illuminate\Database\Connection.php:485
      PDOException::("SQLSTATE[HY000]: General error: 1553 Cannot drop index 'meal_menu_meal_id_foreign': needed in a foreign key constraint")

  2   F:\Laravel\Mealing\vendor\laravel\framework\src\Illuminate\Database\Connection.php:485
      PDOStatement::execute()

**Comment by JustinByrne** [comment]
@wahyusaragih have you downloaded the most up to date version?
